[tool.black]
line-length = 100
target-version = ["py312"]
skip-string-normalization = true
extend-exclude = [
  "/generated/",
  "/wikix.egg-info/",
]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = ["generated", "wikix.egg-info"]

[tool.ruff.lint]
select = ["E", "F", "I", "W", "B", "UP", "C4", "SIM", "Q", "RET", "PTH", "PERF"]
ignore = ["E501"]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["generated", "wikix.egg-info"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true
no_implicit_optional = true
disallow_untyped_defs = false
exclude = "generated|wikix.egg-info"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"


